/* BLUETOOTH */

async function connectBluetooth(){

  try {

    const device =
    await navigator.bluetooth.requestDevice({

      acceptAllDevices:true,

      optionalServices:[
        'battery_service'
      ]
    });

    document.getElementById(
      "btStatus"
    ).innerHTML =
    "🟢 Connected";

    alert(
      "Connected: " + device.name
    );

  } catch(error){

    document.getElementById(
      "btStatus"
    ).innerHTML =
    "🔴 Disconnected";

    alert(
      "Bluetooth Connection Failed"
    );
  }
}

/* PUMP */

function startPump(){

  alert(
    "Medicine Pump Activated"
  );
}

/* AI INSIGHT */

function generateInsight(){

  document.getElementById(
    "insight"
  ).innerHTML =

  "Vitals Stable. " +
  "Patient health is normal.";
}

/* SENSOR DEMO DATA */

setInterval(()=>{

  document.getElementById("hr")
  .innerHTML =

  Math.floor(
    Math.random()*20
  ) + 70 + " bpm";

  document.getElementById("spo2")
  .innerHTML =

  Math.floor(
    Math.random()*5
  ) + 95 + " %";

  document.getElementById("temp")
  .innerHTML =

  (
    Math.random()*2 + 36
  ).toFixed(1) + " °C";

  document.getElementById("glucose")
  .innerHTML =

  Math.floor(
    Math.random()*40
  ) + 90 + " mg/dL";

  document.getElementById("ph")
  .innerHTML =

  (
    Math.random()*2 + 6
  ).toFixed(1);

},2000);
function downloadReport(){

  alert(
    "Patent Report Download Started"
  );
}
/* GPS LOCATION */

let liveLocation = "";

navigator.geolocation.getCurrentPosition(

(position)=>{

  let lat =
  position.coords.latitude;

  let lon =
  position.coords.longitude;

  liveLocation =

  "https://maps.google.com/?q=" +
  lat + "," + lon;

  document.getElementById(
    "locationText"
  ).innerHTML =

  "📍 Location Ready";

});
function sendEmergency(){

  let doctor =
  document.getElementById(
    "doctorNumber"
  ).value;

  let ambulance =
  document.getElementById(
    "ambulanceNumber"
  ).value;

  let patientData =

  "🚨 EMERGENCY ALERT 🚨\n\n" +

  "Heart Rate: " +
  document.getElementById("hr")
  .innerText + "\n" +

  "SpO2: " +
  document.getElementById("spo2")
  .innerText + "\n" +

  "Temperature: " +
  document.getElementById("temp")
  .innerText + "\n" +

  "Glucose: " +
  document.getElementById("glucose")
  .innerText + "\n\n" +

  "Live Location:\n" +
  liveLocation;

  /* CALL DOCTOR */

  window.location.href =
  "tel:" + doctor;

  /* SMS AMBULANCE */

  setTimeout(()=>{

    window.location.href =

    "sms:" + ambulance +

    "?body=" +

    encodeURIComponent(
      patientData
    );

  },3000);

  alert(
    "Emergency Alert Sent"
  );
}
setInterval(()=>{

let hr =
parseInt(
document.getElementById("hr")
.innerText
);

if(hr > 120){

  sendEmergency();
}

},5000);
/* SMART EMERGENCY DETECTION */

setInterval(()=>{

let hr = parseInt(
document.getElementById("hr")
.innerText
);

let spo2 = parseInt(
document.getElementById("spo2")
.innerText
);

let temp = parseFloat(
document.getElementById("temp")
.innerText
);

let glucose = parseInt(
document.getElementById("glucose")
.innerText
);

/* DANGER CONDITIONS */

if(

hr > 130 ||

hr < 45 ||

spo2 < 90 ||

temp > 39 ||

glucose > 250 ||

glucose < 60

){

  document.body.style.border =
  "5
  /* WIFI CONNECT */

function connectWiFi(){

  let wifi =
  document.getElementById(
    "wifiName"
  ).value;

  let pass =
  document.getElementById(
    "wifiPass"
  ).value;

  if(wifi && pass){

    alert(
      "WiFi Connected: " + wifi
    );

  }else{

    alert(
      "Enter WiFi Details"
    );
  }
}
function downloadPatientReport(){

  let report =

  "===== PATIENT REPORT =====\n\n" +

  "Heart Rate: " +
  document.getElementById("hr")
  .innerText + "\n" +

  "SpO2: " +
  document.getElementById("spo2")
  .innerText + "\n" +

  "Temperature: " +
  document.getElementById("temp")
  .innerText + "\n" +

  "Glucose: " +
  document.getElementById("glucose")
  .innerText + "\n" +

  "pH Level: " +
  document.getElementById("ph")
  .innerText + "\n\n" +

  "Status: Stable\n" +

  "Generated By OvaSync AI";

  let blob = new Blob(
    [report],
    {type:"text/plain"}
  );

  let a =
  document.createElement("a");

  a.href =
  URL.createObjectURL(blob);

  a.download =
  "Patient_Report.txt";

  a.click();
}